import { z } from 'zod';
import { Budget } from '@prisma/client';
import { db,ApiError,json,readJson } from './backend';
import { accounts,validate } from './resources';
import { filteredTransactions,range,JoinedTransaction,publicTransaction } from './transactions';
const budgetSchema=z.object({categoryId:z.string().min(1),amount:z.number().int().positive().max(2147483647),month:z.number().int().min(1).max(12),year:z.number().int().min(1900).max(2200)}).strict();
async function enrichBudget(b:Budget){const prefix=`${b.year}-${String(b.month).padStart(2,'0')}`;const [sum,category]=await Promise.all([db.transaction.aggregate({where:{type:'expense',categoryId:b.categoryId,transactionDate:{startsWith:prefix}},_sum:{amount:true}}),db.category.findUnique({where:{id:b.categoryId}})]);const spent=sum._sum.amount??0,percentage=spent/b.amount*100;return {...b,category,spent,percentage,status:percentage>=100?'Over Budget':percentage>=80?'Approaching Limit':'Safe'};}
export async function budgets(params:URLSearchParams){const {month,year,from,to}=range(params);const rows=await db.budget.findMany({where:{month,year},orderBy:[{year:'desc'},{month:'desc'},{createdAt:'asc'}]});const selected=rows.filter(b=>{const start=`${b.year}-${String(b.month).padStart(2,'0')}-01`,end=new Date(Date.UTC(b.year,b.month,0)).toISOString().slice(0,10);return (!from||end>=from)&&(!to||start<=to);});return Promise.all(selected.map(enrichBudget));}
export async function budgetRoute(req:Request,path:string){if(!/^budgets(?:\/[^/]+)?$/.test(path))return;const id=path.split('/')[1];if(req.method==='GET'&&!id)return json({budgets:await budgets(new URL(req.url).searchParams)});if((req.method==='POST'&&!id)||(req.method==='PATCH'&&id)){
  const old=id?await db.budget.findUnique({where:{id}}):null;if(id&&!old)throw new ApiError(404,'Not found');const raw=await readJson(req);const data=old?validate(budgetSchema,{categoryId:old.categoryId,amount:old.amount,month:old.month,year:old.year,...validate(budgetSchema.partial(),raw)}):validate(budgetSchema,raw);const category=await db.category.findUnique({where:{id:data.categoryId}});if(!category||category.type!=='expense')throw new ApiError(400,'Budget category must be expense');const budget=id?await db.budget.update({where:{id},data}):await db.budget.create({data});return json({budget:await enrichBudget(budget)},id?200:201);
}if(req.method==='DELETE'&&id){await db.budget.delete({where:{id}});return json({success:true});}}
function group(rows:JoinedTransaction[],key:(t:JoinedTransaction)=>string){const map=new Map<string,number>();for(const t of rows){const name=key(t);map.set(name,(map.get(name)??0)+t.amount);}return [...map].map(([name,amount])=>({name,amount})).sort((a,b)=>b.amount-a.amount||a.name.localeCompare(b.name));}
export async function summary(req:Request){const params=new URL(req.url).searchParams;const period=range(params);const {transactions:rows}=await filteredTransactions(params);const accountRows=await accounts();const expenses=rows.filter(t=>t.type==='expense'),incomes=rows.filter(t=>t.type==='income');const expense=expenses.reduce((s,t)=>s+t.amount,0),income=incomes.reduce((s,t)=>s+t.amount,0),netCashflow=income-expense;
  const monthly=new Map<string,{month:string,income:number,expense:number,netCashflow:number}>();
  let start=period.from,end=period.to;
  if(period.year){start=start??`${period.year}-${String(period.month??1).padStart(2,'0')}-01`;end=end??new Date(Date.UTC(period.year,period.month??12,0)).toISOString().slice(0,10);}
  const sortedDates=rows.map(t=>t.transactionDate).sort();start=start??sortedDates[0];end=end??sortedDates.at(-1);
  if(start&&end){const cursor=new Date(start.slice(0,7)+'-01T00:00:00Z');while(cursor.toISOString().slice(0,10)<=end){const month=cursor.toISOString().slice(0,7);if(!period.month||cursor.getUTCMonth()+1===period.month)monthly.set(month,{month,income:0,expense:0,netCashflow:0});cursor.setUTCMonth(cursor.getUTCMonth()+1);}}
  for(const t of rows){const month=t.transactionDate.slice(0,7);const entry=monthly.get(month)??{month,income:0,expense:0,netCashflow:0};if(t.type==='income')entry.income+=t.amount;else entry.expense+=t.amount;entry.netCashflow=entry.income-entry.expense;monthly.set(month,entry);}
  const days=start&&end?Math.max(1,(new Date(end+'T00:00:00Z').getTime()-new Date(start+'T00:00:00Z').getTime())/86400000+1):1;
  const biggest=rows.reduce<JoinedTransaction|null>((best,t)=>!best||t.amount>best.amount?t:best,null);
  return json({totalBalance:accountRows.reduce((s,a)=>s+a.currentBalance,0),income,expense,netCashflow,savingRate:income?netCashflow/income*100:0,averageDailySpending:expense/days,accounts:accountRows,spendingByCategory:group(expenses,t=>t.category.name),incomeByCategory:group(incomes,t=>t.category.name),spendingByAccount:group(expenses,t=>t.account.name),monthlyTrend:[...monthly.values()].sort((a,b)=>a.month.localeCompare(b.month)),topMerchants:group(expenses,t=>t.description.trim()).slice(0,10),biggestTransaction:biggest?publicTransaction(biggest):null,budgets:await budgets(params),recentTransactions:rows.slice(0,10).map(publicTransaction)});
}
