import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
process.env.HERMES_API_TOKEN = 'test-api-token';
process.env.DASHBOARD_PASSWORD = 'test-dashboard-password';
process.env.SESSION_SECRET = 'test-secret-with-at-least-thirty-two-characters';
let handler: (r: Request) => Promise<Response>;
async function req(path:string, method='GET', body?:unknown, headers:Record<string,string>={Authorization:'Bearer test-api-token'}) {
  const r = await handler(new Request('http://localhost:3000/api/'+path,{method,headers:{...(body===undefined?{}:{'content-type':'application/json'}),...headers},body:body===undefined?undefined:JSON.stringify(body)}));
  return {status:r.status,data:await r.json(),headers:r.headers};
}
let accountId:string, categoryId:string, incomeCategoryId:string;
test('backend authentication and real seeded database health', async()=>{
  assert.ok(existsSync('src/lib/backend.ts'),'backend handler must exist');
  handler=(await import('../src/lib/backend')).handle;
  assert.deepEqual((await req('health')).data,{status:'ok'});
  assert.deepEqual(await req('transactions','GET',undefined,{}).then(x=>({status:x.status,data:x.data})),{status:401,data:{success:false,error:'Unauthorized'}});
  assert.equal((await req('transactions','GET',undefined,{Authorization:'Bearer wrong'})).status,401);
  assert.equal((await req('session','GET',undefined,{})).data.authenticated,false);
  assert.equal((await req('session','POST',{password:'wrong'},{})).status,401);
  const login=await req('session','POST',{password:'test-dashboard-password'},{});
  assert.equal(login.status,200);
  assert.match(login.headers.get('set-cookie')!,/HttpOnly/);
  const cookie=login.headers.get('set-cookie')!.split(';')[0];
  assert.equal((await req('session','GET',undefined,{cookie})).data.authenticated,true);
  const activeSettings=await req('settings','GET',undefined,{cookie});
  assert.equal(activeSettings.status,200);
  assert.match(activeSettings.headers.get('set-cookie')!,/Set-Cookie|expense_session=/);
  const originalNow=Date.now;
  Date.now=()=>originalNow()+3*60*1000+1;
  try {
    assert.equal((await req('settings','GET',undefined,{cookie})).status,401);
  } finally { Date.now=originalNow; }
  assert.equal((await req('settings','PATCH',{displayName:'Test'},{cookie,origin:'https://evil.test'})).status,403);
  assert.equal((await req('settings','PATCH',{displayName:'Local'},{cookie,origin:'http://127.0.0.1:3010'})).status,200);
});
test('seeded accounts, category CRUD, settings and validation',async()=>{
  const a=await req('accounts'); assert.equal(a.status,200);assert.equal(a.data.accounts.length,4);
  assert.deepEqual(a.data.accounts.map((a:any)=>a.name).sort(),['BRI','Main','Tabungan Bank Jago (GoPay)','blu by BCA'].sort());
  accountId=a.data.accounts.find((a:any)=>a.name==='BRI').id;
  assert.equal(a.data.accounts[0].currentBalance,0);
  const c=await req('categories');assert.equal(c.data.categories.length,19);
  categoryId=c.data.categories.find((c:any)=>c.name==='Makan').id;
  incomeCategoryId=c.data.categories.find((c:any)=>c.name==='Gaji').id;
  const added=await req('accounts','POST',{name:'Test Wallet',type:'ewallet',initialBalance:10000});assert.equal(added.status,201);
  assert.equal((await req('accounts/'+added.data.account.id,'PATCH',{name:'Wallet Updated'})).data.account.name,'Wallet Updated');
  assert.equal((await req('accounts/'+added.data.account.id,'DELETE')).status,200);
  assert.equal((await req('accounts','POST',{name:'X',type:'invalid'})).status,400);
  assert.equal((await req('categories','POST',{name:'X',type:'expense',image:'raw'})).status,400);
  const created=await req('categories','POST',{name:'Test Category',type:'expense',icon:'coffee'});assert.equal(created.status,201);
  assert.equal((await req('categories/'+created.data.category.id,'PATCH',{name:'Edited'})).status,200);
  assert.equal((await req('categories/'+created.data.category.id,'DELETE')).status,200);
  assert.equal((await req('settings')).data.settings.currency,'IDR');
  assert.equal((await req('settings','PATCH',{displayName:'Dsw',theme:'classic-dark'})).data.settings.displayName,'Dsw');
  assert.equal((await req('settings','PATCH',{defaultAccountId:'missing'})).status,400);
});
let transactionId:string;
test('transaction create, duplicate detection, filters, update and referential guards',async()=>{
  const body={type:'expense',amount:35000,description:'Kopi Kenangan',category:'Makan',account:'BRI',transactionDate:'2026-09-06',transactionTime:'09:30',referenceNumber:' REF-123 ',sourceType:'hermes_text'};
  const made=await req('transactions','POST',body);assert.equal(made.status,201);transactionId=made.data.transaction.id;
  assert.equal(made.data.transaction.account.name,'BRI');assert.equal(made.data.transaction.category.name,'Makan');
  assert.equal(made.data.transaction.referenceKey,undefined);
  const duplicate=await req('transactions','POST',{...body,referenceNumber:'ref 123',description:'Other',amount:9});assert.equal(duplicate.status,409);assert.equal(duplicate.data.status,'possible_duplicate');
  assert.equal((await req('transactions','POST',{...body,description:'KOPI-KENANGAN!',referenceNumber:undefined})).status,409);
  assert.equal((await req('transactions','POST',{...body,description:'Kopi Kenangan Jakarta',referenceNumber:undefined})).status,409);
  assert.equal((await req('transactions','POST',{...body,amount:-1})).status,400);
  assert.equal((await req('transactions','POST',{...body,amount:1.2})).status,400);
  assert.equal((await req('transactions','POST',{...body,transactionDate:'2026-02-30'})).status,400);
  assert.equal((await req('transactions','POST',{...body,imageBase64:'raw'})).status,400);
  assert.equal((await req('transactions','POST',{...body,category:'Gaji'})).status,400);
  assert.equal((await req('transactions/'+transactionId,'PATCH',{notes:'morning coffee'})).status,200);
  assert.equal((await req('transactions/'+transactionId,'PATCH',{type:'income'})).status,400);
  assert.equal((await req('transactions?q=September')).data.total,1);
  assert.equal((await req('transactions?q=35.000')).data.total,1);
  assert.equal((await req('transactions?q=morning')).data.total,1);
  assert.equal((await req('transactions?month=8&year=2026')).data.total,0);
  assert.equal((await req('transactions?from=2026-09-01&to=2026-09-30&accountId='+accountId+'&categoryId='+categoryId+'&sourceType=hermes_text&type=expense')).data.total,1);
  assert.equal((await req('transactions?page=0')).status,400);
  assert.equal((await req('accounts/'+accountId,'DELETE')).status,409);
  assert.equal((await req('categories/'+categoryId,'DELETE')).status,409);
  assert.equal((await req('categories/'+categoryId,'PATCH',{type:'income'})).status,409);
  const income=await req('transactions','POST',{type:'income',amount:1000000,description:'September salary',accountId,categoryId:incomeCategoryId,transactionDate:'2026-09-01'});assert.equal(income.status,201);
  const a=(await req('accounts')).data.accounts.find((a:any)=>a.id===accountId);assert.equal(a.currentBalance,965000);assert.equal(a.transactionCount,2);
  const race=await Promise.all([1,2].map(()=>req('transactions','POST',{...body,amount:100,description:'Concurrent merchant',referenceNumber:'race-test'})));
  assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);
  const raceId=race.find(r=>r.status===201)!.data.transaction.id;assert.equal((await req('transactions/'+raceId,'DELETE')).status,200);
});
let budgetId:string;
test('budgets and date scoped dashboard report reflect the ledger',async()=>{
  const budget=await req('budgets','POST',{categoryId,amount:40000,month:9,year:2026});assert.equal(budget.status,201);budgetId=budget.data.budget.id;
  assert.equal(budget.data.budget.spent,35000);assert.equal(budget.data.budget.status,'Approaching Limit');
  assert.equal((await req('budgets','POST',{categoryId,amount:40000,month:9,year:2026})).status,409);
  assert.equal((await req('budgets','POST',{categoryId:incomeCategoryId,amount:40000,month:9,year:2026})).status,400);
  const report=await req('summary?month=9&year=2026');assert.equal(report.status,200);
  assert.equal(report.data.totalBalance,965000);assert.equal(report.data.income,1000000);assert.equal(report.data.expense,35000);assert.equal(report.data.netCashflow,965000);assert.equal(report.data.savingRate,96.5);
  assert.equal(Math.round(report.data.averageDailySpending),1167);
  assert.deepEqual(report.data.spendingByCategory,[{name:'Makan',amount:35000}]);assert.deepEqual(report.data.incomeByCategory,[{name:'Gaji',amount:1000000}]);
  assert.deepEqual(report.data.spendingByAccount,[{name:'BRI',amount:35000}]);assert.equal(report.data.topMerchants[0].name,'Kopi Kenangan');
  assert.equal(report.data.monthlyTrend[0].month,'2026-09');assert.equal(report.data.monthlyTrend[0].netCashflow,965000);
  assert.equal(report.data.biggestTransaction.amount,1000000);assert.equal(report.data.recentTransactions.length,2);
  assert.equal((await req('summary?month=8&year=2026')).data.expense,0);
  assert.equal((await req('budgets/'+budgetId,'PATCH',{amount:30000})).data.budget.status,'Over Budget');
  assert.equal((await req('budgets/'+budgetId,'PATCH',{amount:100000})).data.budget.status,'Safe');
  assert.equal((await req('budgets?month=8&year=2026')).data.budgets.length,0);
});
