import React from 'react';
import {dateLabel, money} from './ledger-model';
import type {Budget, Distribution, Summary, Transaction, Trend} from './ledger-types';

const colors=['#294f40','#8f9b77','#b89b60','#897965','#718c88','#b6b59a','#786b78','#a9806c'];
export function Empty({children}: {children:React.ReactNode}) { return <div className="empty"><span aria-hidden="true" className="empty-mark">—</span><p>{children}</p></div>; }
export function Panel({title,subtitle,children,action,className=''}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode;className?:string}){return <section className={`panel ${className}`}><header className="section-heading"><div><h2>{title}</h2>{subtitle&&<p className="muted tiny">{subtitle}</p>}</div>{action}</header>{children}</section>;}
function DistributionChart({data,title}:{data:Distribution[];title:string}){
 const total=data.reduce((sum,d)=>sum+d.amount,0);
 if(!total)return <Empty>No activity in this period.</Empty>;
 return <div className="distribution"><div className="donut-wrap"><svg role="img" aria-label={`${title}: ${money(total)} across ${data.length} categories`} viewBox="0 0 200 200"><circle cx="100" cy="100" r="72" fill="none" stroke="var(--line)" strokeWidth="23"/>{data.map((d,i)=>{const preceding=data.slice(0,i).reduce((s,v)=>s+v.amount,0)/total*100;return <circle key={`${d.name}-${i}`} cx="100" cy="100" r="72" fill="none" stroke={colors[i%colors.length]} strokeWidth="23" pathLength="100" strokeDasharray={`${d.amount/total*100} ${100-d.amount/total*100}`} strokeDashoffset={-preceding} transform="rotate(-90 100 100)"/>;})}<text x="100" y="96" textAnchor="middle" className="chart-caption">TOTAL</text><text x="100" y="119" textAnchor="middle" className="chart-total">{new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(total)}</text></svg></div><ul className="legend">{data.map((d,i)=><li key={`${d.name}-${i}`}><span className="legend-name"><i style={{background:colors[i%colors.length]}}/>{d.name}</span><span><strong className="figure">{money(d.amount)}</strong><small>{(d.amount/total*100).toFixed(1)}%</small></span></li>)}</ul></div>;
}
function CashBars({income,expense}:{income:number;expense:number}){
 const max=Math.max(income,expense,1);
 return <div className="cashbars"><svg viewBox="0 0 400 155" role="img" aria-label={`Income and expense: income ${money(income)}, expense ${money(expense)}`}><line x1="20" y1="130" x2="380" y2="130" stroke="var(--line)"/>{[0,1,2].map(n=><line key={n} x1="20" y1={25+n*35} x2="380" y2={25+n*35} stroke="var(--line)" strokeDasharray="3 6"/>)}<rect x="95" y={130-income/max*108} width="76" height={income/max*108} fill={colors[0]} rx="2"/><rect x="228" y={130-expense/max*108} width="76" height={expense/max*108} fill={colors[2]} rx="2"/><text x="133" y="151" textAnchor="middle" className="chart-caption">Income</text><text x="266" y="151" textAnchor="middle" className="chart-caption">Expense</text></svg><div className="cashbar-totals"><span><i className="dot green"/>Income<strong className="figure">{money(income)}</strong></span><span><i className="dot brass"/>Expense<strong className="figure">{money(expense)}</strong></span></div></div>;
}
function TrendChart({data}:{data:Trend[]}){
 if(!data.length)return <Empty>No monthly history yet.</Empty>;
 const values=data.flatMap(d=>[d.income,d.expense,d.netCashflow]);const min=Math.min(0,...values),max=Math.max(1,...values),span=max-min;
 const x=(i:number)=>34+i/Math.max(data.length-1,1)*532;
 const y=(n:number)=>145-(n-min)/span*119;
 return <><svg className="trend-chart" viewBox="0 0 600 183" role="img" aria-label="Monthly cash flow: income, expense and net cash flow. Exact amounts in the table below.">{[0,1,2,3].map(i=><line key={i} x1="30" y1={26+i*40} x2="570" y2={26+i*40} stroke="var(--line)" strokeDasharray="3 5"/>)}{(['income','expense','netCashflow'] as const).map((key,j)=><g key={key}><polyline fill="none" stroke={colors[j]} strokeWidth={j===2?2:3} strokeDasharray={j===2?'4 4':undefined} points={data.map((d,i)=>`${x(i)},${y(d[key])}`).join(' ')}/>{data.map((d,i)=><circle key={i} cx={x(i)} cy={y(d[key])} r="3" fill={colors[j]}/>)}</g>)}{data.map((d,i)=><text key={i} x={x(i)} y="176" textAnchor="middle" className="chart-caption">{d.month}</text>)}</svg><div className="chart-key"><span><i style={{background:colors[0]}}/>Income</span><span><i style={{background:colors[1]}}/>Expense</span><span><i style={{background:colors[2]}}/>Net cash flow</span></div><details className="data-details"><summary>View monthly figures</summary><div className="table-scroll"><table><caption className="sr-only">Monthly financial summary</caption><thead><tr><th>Month</th><th>Income</th><th>Expense</th><th>Net cash flow</th></tr></thead><tbody>{data.map(d=><tr key={d.month}><td>{d.month}</td><td className="figure">{money(d.income)}</td><td className="figure">{money(d.expense)}</td><td className="figure">{money(d.netCashflow)}</td></tr>)}</tbody></table></div></details></>;
}
export function BudgetProgress({budget}:{budget:Budget}){const p=Number.isFinite(budget.percentage)?budget.percentage:budget.amount?budget.spent/budget.amount*100:0;const status=p>=100?'over':p>=80?'approaching':'safe';return <div className="budget-progress"><div className="budget-label"><strong>{budget.category?.name||'Uncategorized'}</strong><span className={`badge ${status}`}>{status==='over'?'Over budget':status==='approaching'?'Approaching limit':'On track'}</span></div><div className="progress-track" role="progressbar" aria-label={`${budget.category?.name||'Category'} budget used`} aria-valuenow={Math.min(100,Math.round(p))} aria-valuemin={0} aria-valuemax={100} aria-valuetext={`${p.toFixed(1)}% used`}><span className={status} style={{width:`${Math.min(100,Math.max(0,p))}%`}}/></div><div className="budget-caption"><span><strong className="figure">{money(budget.spent)}</strong> of {money(budget.amount)}</span><strong>{p.toFixed(0)}%</strong></div></div>;}
export function Analytics({summary:s,detailed=false,onNavigate,onEdit}:{summary:Summary;detailed?:boolean;onNavigate:(tab:string)=>void;onEdit:(transaction:Transaction)=>void}) {
 return <><div className="metric-grid"><article className="metric total"><span className="eyebrow">TOTAL BALANCE</span><strong className="metric-value">{money(s.totalBalance)}</strong><span className="metric-note">Across all accounts · all time</span><span aria-hidden="true" className="metric-seal">PEL</span></article><article className="metric"><span className="eyebrow">PERIOD INCOME <span className="positive">↙</span></span><strong className="metric-value">{money(s.income)}</strong><span className="metric-note">Money received</span></article><article className="metric"><span className="eyebrow">PERIOD EXPENSE <span className="negative">↗</span></span><strong className="metric-value">{money(s.expense)}</strong><span className="metric-note">Money spent</span></article><article className="metric"><span className="eyebrow">NET CASH FLOW</span><strong className={`metric-value ${s.netCashflow<0?'negative':'positive'}`}>{money(s.netCashflow)}</strong><span className="metric-note">{Number(s.savingRate||0).toFixed(1)}% saving rate</span></article></div>
 {!detailed&&<Panel title="Your accounts" subtitle="A place for every balance" action={<button className="text-button" onClick={()=>onNavigate('Accounts')}>Manage accounts <span aria-hidden="true">↗</span></button>}>{s.accounts.length?<div className="account-strip">{s.accounts.map(a=><button className="account-mini" key={a.id} onClick={()=>onNavigate('Accounts')}><span className="account-symbol" aria-hidden="true">{a.type==='cash'?'▤':'▥'}</span><span><strong>{a.name}</strong><small className="muted capitalize">{a.type}</small></span><strong className="figure">{money(a.currentBalance)}</strong></button>)}</div>:<Empty>No accounts yet. Add your first account to begin.</Empty>}</Panel>}
 <div className="two-columns"><Panel title="Spending by category" subtitle="Where your money went"><DistributionChart data={s.spendingByCategory} title="Spending by category"/></Panel><Panel title="Income & expense" subtitle="A balanced perspective"><CashBars income={s.income} expense={s.expense}/><div className="insight"><span className="insight-icon" aria-hidden="true">↗</span><p><strong className="figure">{money(s.averageDailySpending)}</strong><span className="muted"> average daily spending in this period</span></p></div></Panel></div>
 <div className="two-columns wide-left"><Panel title="The longer view" subtitle="Monthly income, expense and net cash flow"><TrendChart data={s.monthlyTrend}/></Panel><Panel title="Budget vs. actual" subtitle="A considered approach to spending" action={<button className="text-button" onClick={()=>onNavigate('Budgets')}>Manage <span aria-hidden="true">↗</span></button>}>{s.budgets.length?s.budgets.map(b=><BudgetProgress key={b.id} budget={b}/>):<Empty>No budgets for this month.</Empty>}</Panel></div>
 {detailed&&<><div className="two-columns"><Panel title="Income by category" subtitle="Your sources of income"><DistributionChart data={s.incomeByCategory} title="Income by category"/></Panel><Panel title="Spending by account" subtitle="How you paid"><DistributionChart data={s.spendingByAccount} title="Spending by account"/></Panel></div><div className="two-columns"><Panel title="Top merchants" subtitle="Largest spending destinations">{s.topMerchants.length?<ol className="rank-list">{s.topMerchants.map((m,i)=><li key={`${m.name}-${i}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><span>{m.name}</span><strong className="figure">{money(m.amount)}</strong></li>)}</ol>:<Empty>No merchants in this period.</Empty>}</Panel><Panel title="Biggest transaction" subtitle="The largest single entry">{s.biggestTransaction?<div className="biggest"><span className="badge">{s.biggestTransaction.type}</span><h3>{s.biggestTransaction.description}</h3><strong className="metric-value">{money(s.biggestTransaction.amount)}</strong><p className="muted">{dateLabel(s.biggestTransaction.transactionDate)} · {s.biggestTransaction.account?.name}</p><button onClick={()=>onEdit(s.biggestTransaction!)}>View transaction</button></div>:<Empty>No transactions in this period.</Empty>}</Panel></div></>}
 {!detailed&&<Panel title="Recent transactions" subtitle="The latest entries in your ledger" action={<button className="text-button" onClick={()=>onNavigate('Transactions')}>View all <span aria-hidden="true">↗</span></button>}>{s.recentTransactions.length?<div className="recent-list">{s.recentTransactions.map(t=><button key={t.id} className="recent-item" onClick={()=>onEdit(t)}><span className={`flow-icon ${t.type}`} aria-hidden="true">{t.type==='income'?'↙':'↗'}</span><span className="recent-description"><strong>{t.description}</strong><small>{t.category?.name} · {t.account?.name}</small></span><span className="recent-date muted tiny">{dateLabel(t.transactionDate)}</span><strong className={`figure ${t.type==='income'?'positive':''}`}>{t.type==='income'?'+':'−'}{money(t.amount)}</strong></button>)}</div>:<Empty>No transactions in this period. Your first entry starts the story.</Empty>}</Panel>}
 </>;
}
