"use client";
import React, { useEffect, useRef, useState } from 'react';
import type { Account, Category, Entry, Payload, Resource } from './ledger-types';

export function EntryEditor({kind,entry,accounts,categories,defaultAccountId,month,year,onSave,onClose}: {kind:Resource;entry?:Entry;accounts:Account[];categories:Category[];defaultAccountId?:string|null;month:number;year:number;onSave:(data:Payload)=>Promise<void>;onClose:()=>void}) {
 const [type,setType]=useState<'expense'|'income'>(entry?.type === 'income' ? 'income' : 'expense');
 const [error,setError]=useState('');
 const [busy,setBusy]=useState(false);
 const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null; panel.current?.querySelector<HTMLElement>('input,select,button')?.focus();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return ()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 const singular=kind==='categories'?'category':kind.slice(0,-1);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><div ref={panel} role="dialog" aria-modal="true" aria-labelledby="editor-title" className="editor" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const controls=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]');if(!controls?.length)return;const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header className="section-heading"><div><p className="eyebrow">YOUR PRIVATE RECORD</p><h2 id="editor-title">{entry?.id?'Edit':'New'} {singular}</h2></div><button type="button" aria-label="Close editor" disabled={busy} onClick={onClose} className="icon-button">×</button></header><form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const data:Payload={};new FormData(e.currentTarget).forEach((v,k)=>{data[k]=String(v);});for(const k of ['amount','initialBalance','month','year'])if(k in data)data[k]=Number(data[k]);if(kind==='transactions')data.sourceType=entry?.sourceType||'manual';try{await onSave(data);onClose();}catch(err){setError(err instanceof Error?err.message:'Unable to save. Please try again.');}finally{setBusy(false);}}}>
 {kind==='transactions'&&<><div className="form-grid"><label>Type<select name="type" value={type} onChange={e=>setType(e.target.value as 'expense'|'income')}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Amount (IDR)<input name="amount" type="number" min="1" step="1" required defaultValue={entry?.amount} placeholder="0"/></label></div><label>Description<input name="description" required maxLength={300} defaultValue={entry?.description} placeholder="What was this transaction for?"/></label><div className="form-grid"><label>Account<select name="accountId" required defaultValue={entry?.accountId||defaultAccountId||''}><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Category<select key={type} name="categoryId" required defaultValue={entry?.type===type?entry?.categoryId:''}><option value="">Choose category</option>{categories.filter(c=>c.type===type).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Date<input name="transactionDate" type="date" required defaultValue={entry?.transactionDate?.slice(0,10)||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}/></label><label>Time (optional)<input name="transactionTime" type="time" defaultValue={entry?.transactionTime||''}/></label></div><label>Notes (optional)<textarea name="notes" rows={3} defaultValue={entry?.notes||''}/></label><label>Reference number (optional)<input name="referenceNumber" defaultValue={entry?.referenceNumber||''}/></label>{(!accounts.length||!categories.some(c=>c.type===type))&&<p className="alert">Create an account and a matching {type} category before adding a transaction.</p>}</>}
 {kind==='accounts'&&<><label>Name<input name="name" required maxLength={100} defaultValue={entry?.name} placeholder="e.g. Bank Jago"/></label><label>Account type<select name="type" defaultValue={entry?.type||'bank'}>{['bank','cash','ewallet','investment','other'].map(t=><option key={t} value={t}>{t==='ewallet'?'E-wallet':t[0].toUpperCase()+t.slice(1)}</option>)}</select></label><label>Opening balance (IDR)<input name="initialBalance" type="number" step="1" required defaultValue={entry?.initialBalance??0}/></label><p className="muted tiny">Current balance is calculated from this opening balance and all recorded transactions.</p></>}
 {kind==='categories'&&<><label>Name<input name="name" required maxLength={100} defaultValue={entry?.name} placeholder="e.g. Food & dining"/></label><label>Type<select name="type" defaultValue={entry?.type||'expense'}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Icon label<input name="icon" maxLength={40} defaultValue={entry?.icon||'tag'} placeholder="e.g. coffee, home, transport"/></label><p className="muted tiny">A category groups similar transactions for a clearer financial picture.</p></>}
 {kind==='budgets'&&<><label>Expense category<select name="categoryId" required defaultValue={entry?.categoryId||''}><option value="">Choose category</option>{categories.filter(c=>c.type==='expense').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Monthly limit (IDR)<input name="amount" type="number" min="1" step="1" required defaultValue={entry?.amount} placeholder="0"/></label><div className="form-grid"><label>Month<select name="month" defaultValue={entry?.month||month}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2024,i,1).toLocaleString('en',{month:'long'})}</option>)}</select></label><label>Year<input name="year" type="number" min="1900" max="2100" required defaultValue={entry?.year||year}/></label></div><p className="muted tiny">One budget per expense category, per month. Spending updates automatically.</p></>}
 {error&&<p role="alert" className="alert error">{error}</p>}<footer className="form-actions"><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':`Save ${singular}`}</button></footer></form></div></div>;
}
