import React from 'react';
import {dateLabel, money} from './ledger-model';
import {Empty} from './analytics';
import type {Account,Category,Filters,Transaction} from './ledger-types';
const sources:Record<string,string>={manual:'Manual',hermes_image:'Hermes image',hermes_text:'Hermes text'};
export function Transactions({transactions,total,filters:f,accounts,categories,onFilter,onEdit,onDelete}:{transactions:Transaction[];total:number;filters:Filters;accounts:Account[];categories:Category[];onFilter:(patch:Partial<Filters>)=>void;onEdit:(t:Transaction)=>void;onDelete:(t:Transaction)=>void}){
 const pages=Math.max(1,Math.ceil(total/f.pageSize));
 return <section className="panel transactions-panel"><div className="transaction-toolbar"><label className="search-label"><span className="sr-only">Search transactions</span><span className="search-symbol" aria-hidden="true">⌕</span><input aria-label="Search transactions" type="search" placeholder="Search description, account, month, amount…" value={f.q} onChange={e=>onFilter({q:e.target.value,page:1})}/></label><label className="sort-label">Sort by<select value={f.sort} onChange={e=>onFilter({sort:e.target.value,page:1})}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="largest">Largest amount</option><option value="smallest">Smallest amount</option></select></label></div><div className="filter-grid"><label>Account<select value={f.accountId} onChange={e=>onFilter({accountId:e.target.value,page:1})}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Category<select value={f.categoryId} onChange={e=>onFilter({categoryId:e.target.value,page:1})}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Type<select value={f.type} onChange={e=>onFilter({type:e.target.value,page:1})}><option value="">Income & expense</option><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Source<select value={f.sourceType} onChange={e=>onFilter({sourceType:e.target.value,page:1})}><option value="">All sources</option>{Object.entries(sources).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="text-button" onClick={()=>onFilter({q:'',accountId:'',categoryId:'',type:'',sourceType:'',sort:'newest',page:1})}>Clear filters</button></div><p className="filter-hint muted tiny">Search naturally: “Kopi”, “Jago”, “September” or “25000”. Date filters above still apply.</p>
 {transactions.length?<><div className="transaction-head" aria-hidden="true"><span>TRANSACTION</span><span>ACCOUNT / CATEGORY</span><span>DATE / SOURCE</span><span>AMOUNT</span><span>ACTIONS</span></div><div className="transaction-list">{transactions.map(t=><article key={t.id} className="transaction-card"><div className="transaction-description"><span className={`flow-icon ${t.type}`} aria-hidden="true">{t.type==='income'?'↙':'↗'}</span><div><h3>{t.description}</h3><span className="tiny muted capitalize">{t.type}</span></div></div><div className="transaction-account"><strong>{t.account?.name||'Unknown account'}</strong><span className="tiny muted">{t.category?.name||'Uncategorized'}</span></div><div className="transaction-date"><time dateTime={t.transactionDate}>{dateLabel(t.transactionDate)}</time><span className="tiny muted">{sources[t.sourceType]||t.sourceType}{t.transactionTime?` · ${t.transactionTime}`:''}</span></div><strong className={`transaction-amount figure ${t.type==='income'?'positive':''}`}>{t.type==='income'?'+':'−'}{money(t.amount)}</strong><div className="row-actions"><button aria-label={`Edit ${t.description}`} className="icon-button" onClick={()=>onEdit(t)} title="Edit transaction"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="m15 5 4 4M4 20l4-1L20 7a2.8 2.8 0 0 0-4-4L4 15v5Z"/></svg></button><button aria-label={`Delete ${t.description}`} className="icon-button danger-text" onClick={()=>onDelete(t)} title="Delete transaction"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6m4-6v6"/></svg></button></div>{(t.notes||t.referenceNumber)&&<details className="transaction-details"><summary>Notes & reference</summary>{t.notes&&<p>{t.notes}</p>}{t.referenceNumber&&<p className="tiny muted">Reference: {t.referenceNumber}</p>}</details>}</article>)}</div></>:<Empty>No matching transactions. Try a wider date range or clear your filters.</Empty>}
 <footer className="pagination"><span className="tiny muted">{total===0?'0 transactions':`${(f.page-1)*f.pageSize+1}–${Math.min(f.page*f.pageSize,total)} of ${total} transactions`}</span><label className="page-size">Per page<select value={f.pageSize} onChange={e=>onFilter({pageSize:Number(e.target.value),page:1})}>{[10,20,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select></label><div className="pager"><button aria-label="Previous page" disabled={f.page<=1} onClick={()=>onFilter({page:f.page-1})}>←</button><span className="tiny">Page {f.page} of {pages}</span><button aria-label="Next page" disabled={f.page>=pages} onClick={()=>onFilter({page:f.page+1})}>→</button></div></footer></section>;
}
